### ISSUE TITLE
Slugify not working in cases which use load-doc

### ISSUE THREAD

**Issue by sedflix** [geekSiddharth/student-senate#2]
Slugify is not working in cases where we have used  [loadDoc()](https://github.com/geekSiddharth/student-senate/blob/master/js/embeddedData.js) to load the content from html files. 

Examples:
[https://geeksiddharth.github.io/student-senate/#mail-us](https://geeksiddharth.github.io/student-senate/#mail-us)
[https://geeksiddharth.github.io/student-senate/#who-are-we](https://geeksiddharth.github.io/student-senate/#who-are-we)

**Comment by peey** [comment]
Bhai it works https://geeksiddharth.github.io/student-senate/#mail-us

**Comment by peey** [comment]
Got that from the menu, you also want direct links to work??

**Comment by peey** [comment]
Oh nvm, caching maybe. Doesn't work in private browsing. Looking into it

**Comment by sedflix** [comment]
Thanks  😺

**Comment by peey** [comment]
Now it works! Please verify

**Comment by sedflix** [comment]
![image](https://user-images.githubusercontent.com/21156678/28085322-06f2c684-6699-11e7-9a5c-5bf764ebefb2.png)

**Comment by peey** [comment]
Firefox cache got me again. It should be fixed now, tested in chromium. Please verify and close if it's fixed
